[package]
name = "orbital-database"
version = "0.1.0"
authors = ["T.J. Telan <tjtelan@level11.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4", features = ["postgres"] }
orbital_headers = { path = "../../orbital_headers" }

[lib]
name = "postgres"
path = "mod.rs"