- name: Start all infrastructure containers
  docker_compose:
    state: present
    project_src: /home/vagrant/orbitalci/deploy/infra
    files:
      - docker-compose.yml

# This will mostly accomplish adding tags
- name: Register Consul service into Consul
  consul:
    service_name: "{{ item.name }}"
    service_address: "{{ infra_vagrant_ip }}"
    service_port: "{{ item.port }}"
    tags:
      - vagrant
      - dev
      - configuration
  loop:
    - name: consul
      port: 8500

- name: Register Vault service into Consul
  consul:
    service_name: "{{ item.name }}"
    service_address: "{{ infra_vagrant_ip }}"
    service_port: "{{ item.port }}"
    tags:
      - vagrant
      - dev
      - secrets
  loop:
    - name: vault
      port: 8200

- name: Register Postgresql service into Consul
  consul:
    service_name: "{{ item.name }}"
    service_address: "{{ infra_vagrant_ip }}"
    service_port: "{{ item.port }}"
    tags:
      - vagrant
      - dev
      - database
  loop:
    - name: postgres
      port: 5432

- name: Register NSQ services into Consul
  consul:
    service_name: "{{ item.name }}"
    service_address: "{{ infra_vagrant_ip }}"
    service_port: "{{ item.port }}"
    tags:
      - vagrant
      - dev
      - message-queue
  loop:
    - name: nsqd_tcp
      port: 4150
    - name: nsqd_http
      port: 4151
    - name: nsqlookupd_tcp
      port: 4160
    - name: nsqlookupd_http
      port: 4161
    - name: nsqadmin
      port: 4171
