[workspace]
members = [
    "cli/orb",
    "cli/orb/src/subcommand",
    "lib/config_parser",
    "lib/exec_runtime",
    "lib/orbital_agent",
    "lib/hashicorp_stack",
    "services",
    "models/orbital_database",
]