[workspace]
members = [
    "cli/orb",
    "lib/config_parser",
    "lib/exec_runtime",
    "lib/orbital_agent",
    "lib/hashicorp_stack",
    "services",
    "models/orbital_database",
]

[patch.crates-io]
git-event = { path = "/home/telant/Documents/git-event-rs" }