# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

# Assuming we are running `diesel` from the root of the repo
[print_schema]
file = "models/orbital_database/postgres/schema.rs"