# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

# We can't use this because we have to hand-write our schema due to postgres custom enum
# Assuming we are running `diesel` from the root of the repo
#[print_schema]
#file = "models/orbital_database/postgres/schema.rs"

# This should arrive w/ diesel-rs/diesel#2163
#[migrations_directory]
#file = "src/orbital_database/postgres/migrations"