image = "docker"
env = [ "GLOBAL=yes" ]

[[stages]]
name = "Testing env vars"
env = [ "LOCAL=first" ]
command = [
  "echo Org is ${ORBITAL_ORG}",
  "echo Repo is ${ORBITAL_REPOSITORY}",
  "echo Build number is ${ORBITAL_BUILD_NUMBER}",
  "echo Commit is ${ORBITAL_COMMIT}",
  "echo Commit short is ${ORBITAL_COMMIT_SHORT}",
  "echo Commit message is ${ORBITAL_COMMIT_MSG}"
]

[[stages]]
name = "The second stage"
env = [ "LOCAL=second" ]
command = [ "pwd", "ls", "env" ]

[[trigger_on]]
name = "git-url-parse"
watch-branch = "main"
action = [
  "notify",
  "build orbital>main ENV=somethung",
  "build orbital>dev"
]

[[trigger_on]]
name = "git-event"
watch-branch = "all"
action = "build orbital>all"
