- import_tasks: golang.yml
- import_tasks: protobuf.yml

#- import_tasks: user_env_var.yml

# TODO: Migrate away from setup-cv.sh
# Instead, set up Consul first, then set up Vault
# For now, keep this structure. Assuming the consul_setup is just calling setup-cv
- import_tasks: vault_setup.yml
- import_tasks: consul_setup.yml

- import_tasks: postgres_setup.yml
- import_tasks: nsq_setup.yml

- import_tasks: orbital_build.yml
- import_tasks: orbital_consul_register.yml

- import_tasks: orbital_systemd.yml
