- name: Run script for initializing Consul + Vault
  shell: |
    export CONSUL_HTTP_ADDR=http://{{ infra_vagrant_ip }}:8500
    export VAULT_ADDR=http://{{ infra_vagrant_ip }}:8200
    export VAULT_TOKEN=ocelotdev
    export DBHOST={{ infra_vagrant_ip }}
    ./setup-cv.sh
  args:
    executable: /bin/bash
    chdir: /home/vagrant/go/src/github.com/level11consulting/ocelot/scripts
