- name: Run HTTP calls for initializing NSQ with build topic
  uri:
    url: "{{ item }}"
    method: POST
  loop:
    - http://192.168.56.78:4151/topic/create?topic=build
    - http://192.168.56.78:4151/channel/create?topic=build&channel=werker
