- name: Add Ocelot related environment variables into global bashrc
  become: yes
  blockinfile:
    path: /etc/bash.bashrc
    block: |
      export {{ item.env_var }}={{ item.value }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK ${{ item.env_var }}"
  loop:
    - env_var: "GOPATH"
      value: "{{ go.path }}"
    - env_var: "GO111MODULE"
      value: "{{ go.use_modules }}"
    - env_var: "PATH"
      value: "{{ path }}"
    - env_var: "VAULT_TOKEN"
      value: "{{ vault.token }}"
    - env_var: "VAULT_ADDR"
      value: "{{ vault.addr }}"
    - env_var: "CONSUL_HTTP_ADDR"
      value: "{{ consul.http_addr }}"
    - env_var: "CONSUL_HOST"
      value: "{{ consul.host }}"
    - env_var: "NSQLOOKUPD_IP"
      value: "{{ nsq.lookupd_ip }}"
    - env_var: "NSQD_IP"
      value: "{{ nsq.nsqd_ip }}"
    - env_var: "REGISTER_IP"
      value: "{{ ocelot.register_ip }}"
    - env_var: "LOG_LEVEL"
      value: "{{ ocelot.log_level }}"
    - env_var: "DBHOST"
      value: "{{ ocelot.dbhost }}"
    - env_var: "ADMIN_HOST"
      value: "{{ ocelot.admin_host }}"
    - env_var: "ADMIN_PORT"
      value: "{{ ocelot.admin_port }}"
