version: "3.3"
services:
  nsqlookupd:
    image: nsqio/nsq
    container_name: nsqlookupd
    command: >
      /nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  nsqd:
    image: nsqio/nsq
    container_name: nsqd
    depends_on:
      - nsqlookupd
    command: >
      /nsqd
      -broadcast-address 192.168.56.78
      -lookupd-tcp-address nsqlookupd:4160
    ports:
      - 4150:4150
      - 4151:4151
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  nsqadmin:
    image: nsqio/nsq
    container_name: nsqadmin
    depends_on:
      - nsqlookupd
    command: >
      /nsqadmin
      -lookupd-http-address nsqlookupd:4161
    ports:
      - 4171:4171
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
networks:
  default:
    external:
      name: ocelot
