version: "3.3"
services:
  db:
    image: postgres
    container_name: db
    hostname: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
networks:
  default:
    external:
      name: orbital
