version: "3.3"
services:
  vault:
    image: vault:1.0.0
    container_name: vault
    hostname: vault
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_DEV_ROOT_TOKEN_ID: orbital
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - 8200:8200
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ./docs/docker-compose/vault-consul/tools/wait-for-it.sh:/wait-for-it.sh
      - ./docs/docker-compose/vault-consul/config/vault:/config
      - ./docs/docker-compose/vault-consul/config/vault/policies:/policies
    entrypoint: vault server -dev
    #entrypoint: /wait-for-it.sh -t 20 -h consul -p 8500 -s -- vault server -config=/config/with-consul.hcl
networks:
  default:
    external:
      name: orbital
