[package]
name = "orbital_services"
version = "0.1.0"
authors = ["T.J. Telan <t.telan@gmail.com>"]
edition = "2018"

[dependencies]
tonic = { version = "0.1.0-alpha.6", features = [ "rustls"] }
orbital_headers = { path = "../models/orbital_headers" }
tokio = "=0.2.0-alpha.6"
git_meta = { path = "../lib/git_meta" }
config_parser = { path = "../lib/config_parser" }
agent_runtime = { path = "../lib/agent_runtime" }
log = "0.4"
futures = "0.3"
prost-types = "0.5"
hashicorp_stack = { path = "../lib/hashicorp_stack" }

[lib]
name = "orbital_services"
path = "mod.rs"