- name: Install docker python modules
  pip:
    name: docker
    state: present
- name: Create Ocelot docker network
  docker_network:
    name: ocelot

- name: Start postgres
  docker_service:
    state: present
    project_src: ./go/src/github.com/level11consulting/ocelot/deploy/infra
    files:
      - postgres-docker-compose.yml

- name: Start NSQ services
  docker_service:
    state: present
    project_src: ./go/src/github.com/level11consulting/ocelot/deploy/infra
    files:
      - nsq-docker-compose.yml

- name: Start Consul
  docker_service:
    state: present
    project_src: ./go/src/github.com/level11consulting/ocelot/deploy/infra
    files:
      - consul-docker-compose.yml

- name: Start Vault
  docker_service:
    state: present
    project_src: ./go/src/github.com/level11consulting/ocelot/deploy/infra
    files:
      - vault-docker-compose.yml
