- name: Create Ocelot docker network
  docker_network:
    name: ocelot

- import_tasks: consul.yml # This task should be first. The other tasks register into Consul
- import_tasks: vault.yml
- import_tasks: postgres.yml
- import_tasks: nsq.yml
