- name: Start Vault
  docker_service:
    state: present
    project_src: ./go/src/github.com/level11consulting/ocelot/deploy/infra
    files:
      - vault-docker-compose.yml

- name: Register Vault service into Consul
  consul:
    service_name: "{{ item.name }}"
    service_address: 192.168.56.78
    service_port: "{{ item.port }}"
    tags:
      - vagrant
      - dev
      - secrets
  loop:
    - name: vault
      port: 8200
