- name: Install common tools
  become: yes
  package:
    state: present
    name: "{{ item }}"
  loop:
    - build-essential
    - unzip
    - vim
    - python3-pip
    - zip

- name: Install python modules that Ansible requires
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - python-consul
    - docker


# Check for docker-compose, if it isn't installed then install it. Otherwise skip the step
#- name: (Workaround) Docker-compose via pip seg faults, but still is successful? Go figure, but check on this later...
#  pip:
#    name: "docker-compose"
#    state: present
#  ignore_errors: yes

# FIXME: This should be split up to use get_url first, for checksum verification
# https://learn.hashicorp.com/vault/operations/ops-deployment-guide
- name: Download our Hashicorp dependencies
  vars:
    consul:
      version: 1.5.0
    vault:
      version: 1.1.2
  become: yes
  unarchive:
    src: "{{ item.url }}"
    dest: /usr/local/bin 
    creates: "{{ item.filepath }}"
    remote_src: yes
  loop:
    - url: "https://releases.hashicorp.com/consul/{{ consul.version }}/consul_{{ consul.version }}_linux_amd64.zip"
      filepath: /usr/local/bin/consul
    - url: "https://releases.hashicorp.com/vault/{{ vault.version }}/vault_{{ vault.version }}_linux_amd64.zip"
      filepath: /usr/local/bin/vault 

# FIXME: Need to figure out what I can use to skip this if it doesn't need to be run.
#- name: Install vault auto-complete
#  shell: vault -autocomplete-install
