[package]
name = "orbital_cli_subcommand"
version = "0.1.0"
authors = ["T.J. Telan <t.telan@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
clap = "2.33"
agent_runtime = { path = "../../../../lib/agent_runtime" }
config_parser = { path = "../../../../lib/config_parser" }
git_meta = { path = "../../../../lib/git_meta" }
orbital_headers = { path = "../../../../models/orbital_headers" }
orbital_services = { path = "../../../../services" }
orbital_database = { path = "../../../../models/orbital_database" }
log = "0.4"
tonic = "0.1.0"
git2 = "0.11"
anyhow = "1.0"
# Temporary. Move into agent runtime
hashicorp_stack = { path = "../../../../lib/hashicorp_stack" }

[lib]
name = "subcommand"
path = "mod.rs"