{{- if .Values.admin.ingress.enabled -}}
{{- $fullName := include "ocelot.fullname" . -}}
{{- $servicePort := .Values.admin.service.port -}}
{{- $ingressPath := .Values.admin.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "ocelot.name" . }}
    chart: {{ template "ocelot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.admin.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.admin.ingress.tls }}
  tls:
  {{- range .Values.admin.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.admin.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-admin
              servicePort: http
  {{- end }}
{{- end }}
---
{{- if .Values.admin.grpcIngress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/grpc-backend: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: admin-{{ template "ocelot.fullname" . }}-grpc
spec:
  rules:
  - host: {{ .Values.admin.grpcIngress.host }}
    http:
      paths:
      - backend:
          serviceName: admin-{{ template "ocelot.fullname" . }}-internal
          servicePort: grpc
  tls:
  - hosts:
    - {{ .Values.admin.grpcIngress.host }}
    secretName: {{ .Values.admin.grpcIngress.tlsSecret }}
{{- end }}
---
{{- if .Values.hookhandler.ingress.enabled -}}
{{- $fullName := include "ocelot.fullname" . -}}
{{- $servicePort := .Values.hookhandler.service.port -}}
{{- $ingressPath := .Values.hookhandler.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "ocelot.name" . }}
    chart: {{ template "ocelot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.hookhandler.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.hookhandler.ingress.tls }}
  tls:
  {{- range .Values.hookhandler.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.hookhandler.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}