# FIXME: Can this be idempotent? Right now it might lose existing secrets on re-run
# NOTE: This is using shell module, so it can use the new environment vars
- name: Reconfigure Vault to use kv v1
  shell: |
    export VAULT_ADDR={{ vault.addr }}
    export VAULT_TOKEN={{ vault.token }}
    {{ item }}
  loop:
    - "vault secrets disable secret"
    - "vault secrets enable -path=secret -version=1 kv"

#TODO: This should also set up the vault stuff that is done in setup-cv.sh
