- name: Start Consul
  docker_service:
    state: present
    project_src: /home/vagrant/orbitalci/deploy/infra
    files:
      - consul-docker-compose.yml

# This will mostly accomplish adding tags
- name: Register Consul service into Consul
  consul:
    service_name: "{{ item.name }}"
    service_address: "{{ infra_vagrant_ip }}"
    service_port: "{{ item.port }}"
    tags:
      - vagrant
      - dev
      - configuration
  loop:
    - name: consul
      port: 8500
