- name: Start postgres
  docker_service:
    state: present
    project_src: /home/vagrant/orbitalci/deploy/infra
    files:
      - postgres-docker-compose.yml

- name: Register Postgre service into Consul
  consul:
    service_name: "{{ item.name }}"
    service_address: "{{ infra_vagrant_ip }}"
    service_port: "{{ item.port }}"
    tags:
      - vagrant
      - dev
      - database
  loop:
    - name: postgres
      port: 5432
