- name: Start Vault
  docker_service:
    state: present
    project_src: /home/vagrant/orbitalci/deploy/infra
    files:
      - vault-docker-compose.yml

- name: Register Vault service into Consul
  consul:
    service_name: "{{ item.name }}"
    service_address: "{{ infra_vagrant_ip }}"
    service_port: "{{ item.port }}"
    tags:
      - vagrant
      - dev
      - secrets
  loop:
    - name: vault
      port: 8200
