version: "3.5"
services:
  # Run `make docker-build` first before running docker-compose up
  # Orbital services
  admin:
    image: orbitalci
    container_name: admin
    command: /usr/local/bin/admin -log-level=debug
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "10000:10000"
    networks:
      - orbital
    environment:
      CONSUL_HOST: consul
      CONSUL_HTTP_ADDR: http://consul:8500
      NSQLOOKUPD_IP: nsqlookupd
      NSQD_IP: nsqd
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_ADDR: http://vault:8200

  hookhandler:
    image: orbitalci
    container_name: hookhandler
    command: /usr/local/bin/hookhandler
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "8088:8088"
    networks:
      - orbital
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      CONSUL_HOST: consul
      LOG_LEVEL: debug
      NSQD_IP: nsqd
      NSQLOOKUPD_IP: nsqlookupd
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN}

  werker:
    image: orbitalci
    container_name: werker
    command: /usr/local/bin/werker -log-level debug
    ports:
      - "9090:9090"
      - "9099:9099"
    networks:
      - orbital
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_ADDR: http://vault:8200
      CONSUL_HTTP_ADDR: http://consul:8500
      CONSUL_HOST: consul
      NSQD_IP: nsdq
      NSQLOOKUPD_IP: nsqlookupd
      REGISTER_IP: 10.1.62.38
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  poller:
    image: orbitalci
    container_name: poller
    command: /usr/local/bin/poller
    networks:
      - orbital
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      CONSUL_HOST: consul
      CONSUL_HTTP_ADDR: http://consul:8500
      NSQD_IP: nsqd
      NSQLOOKUPD_IP: nsqlookupd
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# This network is created first starting deploy/infra/docker-compose.yml
networks:
  orbital:
    external: true