image: docker.metaverse.l11.com/ocelot/base:latest
buildTool: go
notify:
  slack:
    channel: "@jessishank"
    identifier: "ocelot-base"
    on:
      - "PASS"
      - "FAIL"
branches:
  - ALL
env:
  - "OCELOT_PATH=src/github.com/shankj3/ocelot"
stages:
  - name: check ssh file
    script: 
     - ls -ltr ~/.ssh
  - name: triggered
    trigger:
      branches:
      - creds_to_postgres
    script:
      - echo "this should only happen on master"
      - cat ~/.docker/config.json
      - if [ -f ~/.kube/config ]; then kubectl cluster-info; else echo "no kubeconfig"; fi
  - name: be_useful
    script:
      - echo "building $BUILD_ID with has $GIT_HASH"
  - name: go_stuff
    script:
      - cp -r $GOPATH/$OCELOT_PATH/vendor .
      - rm -rf $GOPATH/$OCELOT_PATH/* && cp -r . $GOPATH/$OCELOT_PATH
  - name: testing
    env:
      - "BUILDSERVERHACK=0"
    script:
      - cd $GOPATH/$OCELOT_PATH
      - go test ./... -cover -short
  - name: build
    script:
      - cd $GOPATH/$OCELOT_PATH
      - scripts/build-release-server.sh
