ersion: "3.5"
services:
  vault:
    image: vault:1.1.2
    container_name: vault
    hostname: vault
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_DEV_ROOT_TOKEN_ID: orbital
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - 8200:8200
    networks:
      - orbital
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    # TODO: Dev mode automatically uses kv version 2, which Orbital doesn't support yet. 
    #       Either fix the code to support v2, or manually switch to v1 after starting.
    #       Example workaround:
    #       export VAULT_ADDR=http://0.0.0.0:8200
    #       export VAULT_TOKEN=orbital
    #       vault secrets disable secret
    #       vault secrets enable -path=secret -version=1 kv
    entrypoint: vault server -dev
  consul:
    image: consul:1.5.0
    container_name: consul
    hostname: consul
    command: agent -dev -client 0.0.0.0
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:53/udp
    networks:
      - orbital
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  db:
    image: postgres
    container_name: db
    hostname: db
    ports:
      - 5432:5432
    networks:
      - orbital
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
  nsqlookupd:
    image: nsqio/nsq
    container_name: nsqlookupd
    command: >
      /nsqlookupd
      -broadcast-address 192.168.56.78
    ports:
      - 4160:4160
      - 4161:4161
    networks:
      - orbital
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  nsqd:
    image: nsqio/nsq
    container_name: nsqd
    depends_on:
      - nsqlookupd
    command: >
      /nsqd
      -broadcast-address 192.168.56.78
      -lookupd-tcp-address nsqlookupd:4160 
      -lookupd-tcp-address 192.168.56.78:4160 
    ports:
      - 4150:4150
      - 4151:4151
    networks:
      - orbital
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  nsqadmin:
    image: nsqio/nsq
    container_name: nsqadmin
    depends_on:
      - nsqlookupd
    command: >
      /nsqadmin
      -lookupd-http-address nsqlookupd:4161
      -lookupd-http-address 192.168.56.78:4161
    ports:
      - 4171:4171
    networks:
      - orbital
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  orbital:
    name: orbital
