version: "3.3"
services:
  hookhandler:
    image: ocelot-hookhandler
    build:
      context: ../../
      dockerfile: Dockerfile
      cache_from:
        - golang:1.9-alpine
    environment:
      VAULT_TOKEN: secrets? ooowee
